springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    with-credentials: true

    # ğŸ”½ CDNì„ ì‚¬ìš©í•˜ì§€ ì•Šê³  ë¡œì»¬ ë¦¬ì†ŒìŠ¤ë§Œ ì“°ë„ë¡ ì„¤ì •
    disable-swagger-default-url: true
    use-root-path: true
    config-url: /v3/api-docs/swagger-config

    # (ì˜µì…˜) UI ì •ë ¬ ë°©ì‹
    operationsSorter: method
    tagsSorter: alpha